### ISSUE TITLE
Clicking on Segment should navigate to that point in the show

### ISSUE THREAD

**Issue by wigster** [expectingtofly/LMS_BBC_Sounds_Plugin#10]
BBC sounds 1.1.0 
LMS 8.0.0
Windows Server 2012R2

The Segment times list seems to provide a nice track list for the shows that I listen to. It would be nice if it were possible to jump directly to that point in the show on clicking a segment time. 

Currently (in the Material skin at least), on clicking the Segment a box appears with the segment's title, but nothing else seems to happen.

**Comment by expectingtofly** [comment]
Currently the segment list is provided by the BBC Iplayer plugin in the current version, hence why its not working for BBC Sounds.  This will no longer be the case in the upcoming release 2.0.0.  
I'll look at providing similar segment capability in the future.

**Comment by hestbank** [comment]
Thanks for implementing the Tracklist. Would it be possible to:

- View the Tracklist while playing the programme, ie from the Now Playing menu and
- Display the times in the programme associated with each track (segment times).

Not seeing either of these in LMS web, Android Sqeezer or Windows Squeeze Control .

**Comment by expectingtofly** [comment]
> Thanks for implementing the Tracklist. Would it be possible to:
> 
> * View the Tracklist while playing the programme, ie from the Now Playing menu and
> * Display the times in the programme associated with each track (segment times).
> 
> Not seeing either of these in LMS web, Android Squeezer or Windows Squeeze Control .
> v2.7.0

Sure I can do that.  Although I did find the accuracy of the track times varied quite a lot (depending on the type of programme),  I  believe the track times are set as the programme is broadcast a lot of the time, but the catchup programme quite often has bits chopped off the front,  sometimes making them up to 3 minutes out.

**Comment by hestbank** [comment]
> Sure I can do that. Although I did find the accuracy of the track times varied quite a lot (depending on the type of programme), I believe the track times are set as the programme is broadcast a lot of the time, but the catchup programme quite often has bits chopped off the front, sometimes making them up to 3 minutes out.

Great. In this case I don't think the exact timing is important, just being able to navigate around a three hour programme would be helpful. Although, obviously, the inaccuracy shows up when displaying "Track Now Playing". Not sure how you get round that! 
Thanks.

**Comment by expectingtofly** [comment]
> > Sure I can do that. Although I did find the accuracy of the track times varied quite a lot (depending on the type of programme), I believe the track times are set as the programme is broadcast a lot of the time, but the catchup programme quite often has bits chopped off the front, sometimes making them up to 3 minutes out.
> 
> Great. In this case I don't think the exact timing is important, just being able to navigate around a three hour programme would be helpful. Although, obviously, the inaccuracy shows up when displaying "Track Now Playing". Not sure how you get round that!
> Thanks.

Reading back through this, I realised that you might not have noticed that selecting any track in the menu plays the programe at the point the BBC say the track is,  enabling you to navigate easily?

**Comment by hestbank** [comment]
Thanks, yes I have discovered that. 
It would be great if "Tracklist" appeared in the Now Playing Menu (the one that has items such as Remove from playlist, More Info, On Spotify etc) rather than having to go back to Programme Menu which, if I have been doing something else (eg checking the weather map) on the Touch etc may not always be a simple back arrow. 
As for segment times, they would be an added luxury. If you've had a 6Music programme on, and you've not been concentrating, and then the News comes on which you want to miss, then you don't know which track to go to. With the segment times you can go to the track nearest 33 mins or 1 hr 33 mins and know you are in the right place. Like I say, a luxury, but a nice one!
Thanks for all your hard work.

**Comment by expectingtofly** [comment]
Implemented
