### ISSUE TITLE
Problems with Position Syncing wrt BBC site

### ISSUE THREAD

**Issue by wigster** [expectingtofly/LMS_BBC_Sounds_Plugin#12]
Hi

Just upgraded to v2. LMS 8.0.0.

When I play a show on LMS and stop, its position is immediately synched up to the BBC as you've designed it to be. However the sync the other way does not seem to work.

To replicate: 

1) Go to e.g. https://www.bbc.co.uk/sounds/play/m000p0dg, choose a position halfway and close the tab. Pause, wait a few secs and close tab.
2) Find the same show in LMS, (I navigated through Latest for my account; maybe this matters). Play. It will start playing from the beginning. 
3) If this show is already open in LMS, selecting play from the BBC Sounds menu will just continue from where LMS left off, instead of updating to the new position.

Sorry: I just realised ther eis a continue listening option! I'm closing.

**Comment by expectingtofly** [comment]
I'm reopening :-)  
This should work as you describe
