### ISSUE TITLE
Schedule only showing regional stations

### ISSUE THREAD

**Issue by T1moth** [expectingtofly/LMS_BBC_Sounds_Plugin#121]
Today the stations and schedules list suddenly lost all the national stations. This is only on LMS I have tried Sounds on other devices and it is all there.

**Comment by T1moth** [comment]
> 

Sorry, can you point me at some instructions for how to apply the fix. I have no experience whatsoever.

**Comment by expectingtofly** [comment]
> > 
> 
> Sorry, can you point me at some instructions for how to apply the fix. I have no experience whatsoever.

It's in the main repository.  So you just need to update the plugin in the standard way.
Go to your local LMS instance.  Go to    Settings->Plugins    You will then see the BBC Sounds plugin update, select it and click apply.
