### ISSUE TITLE
National stations vanished from Stations and Schedules

### ISSUE THREAD

**Issue by marrem** [expectingtofly/LMS_BBC_Sounds_Plugin#122]
I only see regional stations in this section since yesterday 22nd June   
Before that date it worked fine showing also the national networks.

**Comment by expectingtofly** [comment]
> I only see regional stations in this section since yesterday 22nd June Before that date it worked fine showing also the national networks.

This is fixed in versio 2.25.1.  please update to the latest version.  See the discussion on the forum here: https://forums.slimdevices.com/showthread.php?113045-Announce-BBC-Sounds-Plugin&p=1056683&viewfull=1#post1056683
.

**Comment by marrem** [comment]
I ‘ll update. Thanks.

**Comment by expectingtofly** [comment]
> Seems to be fixed, issue should be closed?

This is a duplicate, so I've left this one open for a bit as people don't see the closed one.

**Comment by marrem** [comment]
I have updated and can confirm that I see national stations again. I ran into the issue the day before yesterday. I didn't expect a fix had already been made. Thanks very much. The plugin is much appreciated. I listen a lot to the BBC and with the plugin I can comfortably listen without draining my phone battery running the official BBC app.

I'll leave the issue open, so you can close it when you see fit.

**Comment by expectingtofly** [comment]
Duplicate
