### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by wigster** [expectingtofly/LMS_BBC_Sounds_Plugin#13]
(A low-priority enhancement?)

It would be nice to be able to have access to the BBC accounts of more than one user, in a family-type situation.

E.g. spotty handles this by giving an extra menu, where the active account can be swapped, rather than combining everything. And then the active account is defined per player, so e.g. in my study it's always my account, and in the living room, a different one.

**Comment by expectingtofly** [comment]
Unfortunately, due to the way the plugin relies on LMS's cookie management system for authorisation, it is not possible to have more than one account stored.  This won't be possible on this plugin.  So, unfortunately, closing.
