### ISSUE TITLE
BBC Sounds seem like they're terminating access

### ISSUE THREAD

**Issue by NohWayJose** [expectingtofly/LMS_BBC_Sounds_Plugin#131]
I've started getting messages from the BBC Sounds plugin saying the stream will stop working in 2023. I hope this is something you/we can work around as my house runs entirely on Raspberry Pis and JustBoom sound hats and I only really listen to BBC radio 1 & 4.

**Comment by expectingtofly** [comment]
The good news is I think you are mistaken (I hope!) and you are listening to the old mp3 streams that are ending in 2023 that you maybe have saved as a favourite.  Make sure you select the live radio station from the Stations & Schedules menu in BBC Sounds plugin menu.  You can add that stream to your favourites or presets.

You will also find that the live streams from BBC Sounds have much more functionality than the old mp3 streams.   You can pause and rewind live radio and skip back to start of programmes and skip back to previous programmes.

**Comment by NohWayJose** [comment]
I thought I was on live but I'll check it out to make sure. In the meantime, here's a BBC Sounds link about cessation of the Shoutcast protocol to concentrate on HLS & DASH.
https://www.bbc.co.uk/sounds/help/questions/recent-changes-to-bbc-sounds/shoutcast-closure

**Comment by expectingtofly** [comment]
> I thought I was on live but I'll check it out to make sure. In the meantime, here's a BBC Sounds link about cessation of the Shoutcast protocol to concentrate on HLS & DASH. https://www.bbc.co.uk/sounds/help/questions/recent-changes-to-bbc-sounds/shoutcast-closure

That's correct.   This BBC Sounds Plugin only has the ability to use the DASH streams and uses nothing else.  It does not use the Shoutcast streams
