### ISSUE TITLE
BBC Sounds to stop working in 2023?

### ISSUE THREAD

**Issue by SteveJSmythe** [expectingtofly/LMS_BBC_Sounds_Plugin#139]
I am getting a warning message over your BBC Sounds plugin. See https://radio.co/blog/bbc-sounds-stop-working

**Comment by expectingtofly** [comment]
As far as I know, that message is only appearing on the mp3 shoutcast live streams, which are ending in 2023.  
Not the live streams that are played via the plugin, which does not use the shoutcast streams.
Are you sure you are listening via plugin?  Perhaps you are listening via a preset or favourite that has been bookmarked from elsewhere?

You can check by clicking on M on the station in the playlist, if the url does not look like this, then you are not playing via the plugin:

![image](https://user-images.githubusercontent.com/73394021/214886483-c048e046-af51-4428-8601-77b702454852.png)

**Comment by SteveJSmythe** [comment]
I think you are right. I installed the BBC Sounds plugin today and thought I had logged in but it turns out I wasn't logged in after all. I must have been listening to a shoutcast stream without realising. Thanks.

**Comment by expectingtofly** [comment]
Yes, you will need to log in.  Then you need to set up your presets and favourites by selecting the live station from "Stations & Schedules" in the menu.

**Comment by SteveJSmythe** [comment]
All done. Thanks.
