### ISSUE TITLE
Can't play radio progarms being broadcast

### ISSUE THREAD

**Issue by Rich28** [expectingtofly/LMS_BBC_Sounds_Plugin#144]
Hi, absoloutely fantastic plugin but for some reason I seem unable to play programs (via 'Stations & Schedules') that are being broadcast live. i first noticed this issue last week when I was hoping to rewind Radio 4's News at One program to the start and c. 1:15pm  (still being broadcast), which I couldn't get to work at all.  Hope that makes sense and is something that's easy to resolve.  Thanks.

**Comment by expectingtofly** [comment]
Oh right, that should work fine. It works form me.  Are there any errors in the LMS log?

Anyway, the easiest way to rewind the currently live program, that I always use, is.  Just play the live radio station, then press << in your controller and that will rewind to the start of the currently playing programme.  You can also keep pressing << and it will skip through the previous programmes up to 5 hours in the past.  For full details see the wiki : https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin/wiki

**Comment by Rich28** [comment]
Thanks for getting back to me and for your helpful reponse . I've just moved to LMS and still finding myself around and as things transpire I can't replicate the issue I reported, so will close this.  Once again thanks for your help
