### ISSUE TITLE
Live not working anymore 

### ISSUE THREAD

**Issue by marrem** [expectingtofly/LMS_BBC_Sounds_Plugin#157]
Live stopped working for all channels since today. Has been working for a year without any issues. On demand still works.

**Comment by expectingtofly** [comment]
I presume you are using an old version of the plugin?
For live to work you need to be using version 2.32.0 or higher?   Update to the latest version.

**Comment by marrem** [comment]
Sorry. I forgot to update.

**Comment by marrem** [comment]
I close the ticket.
