### ISSUE TITLE
Account Logi issue

### ISSUE THREAD

**Issue by xsiv-one** [expectingtofly/LMS_BBC_Sounds_Plugin#158]
Had a need to re-enter my login details, but the plugin is now reporting a problem 
 There was a problem with sign in, please try again

Have friend running similar setup and he to is getting the same message.

The plugin had been working without issue earlier, has something changed?

Here are details of my server.

Logitech Media Server Version: 8.4.0 - 0.1.20230420git1680780553 @ Thu Apr 20 13:24:44 EDT 2023
Hostname: s7netserver
Server IP Address: 192.168.1.19
Server HTTP Port Number: 9000
Operating system: Red Hat - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.24.3 - x86_64-linux-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.038
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 9

**Comment by expectingtofly** [comment]
Hi
There is indeed a problem.   A fix is being worked on.

**Comment by expectingtofly** [comment]
This is fixed in version 2.32.2.  It is available in the beta repository now.  It will be available to update from the main repository at the next refresh later today.

**Comment by davidtlewis** [comment]
I also saw this issue .  The latest version fixed it for me.  Thanks very much for the great work @expectingtofly

**Comment by xsiv-one** [comment]
That's fantastic work @expectingtofly, back up and running!
