### ISSUE TITLE
API endpoint to get the tracklist of a (non-available) program ?

### ISSUE THREAD

**Issue by spiff-radio** [expectingtofly/LMS_BBC_Sounds_Plugin#160]
Hello !
I found your code while searching for informations about the BBC API endpoints.
It is not directly related to your plugin (sorry); but maybe you could help me here.

I can use this endpoint to retrieve the tracklist of a playable programme (check for a prop named `aod_tracks`).
`https://rms.api.bbc.co.uk/v2/experience/inline/play/${pid}`
eg.
https://www.bbc.co.uk/programmes/m001rn3c -->
https://rms.api.bbc.co.uk/v2/experience/inline/play/m001rn3c

Once the programme is not playable anymore, this endpoint does not work anymore; even if the webpage still shows up the tracklist.
eg.
https://www.bbc.co.uk/programmes/m001g7x7 -->
https://rms.api.bbc.co.uk/v2/experience/inline/play/m001g7x7
gives
`Playable Not Found`

Are you aware of an endpoint I could use to retrieve the tracklist of those non-playable items ?

Thanks a lot !

**Comment by expectingtofly** [comment]
Sorry,  I have no idea.  Also, considering the API purpose, can't think of a reason why that would be available in their api
