### ISSUE TITLE
Automatic play on LMS Restart 

### ISSUE THREAD

**Issue by wigster** [expectingtofly/LMS_BBC_Sounds_Plugin#33]
One funny thing that is happening with at least v2.5.2 and 2.6.0 on LMS 8 nightly on Windows.

If I have a BBC Sounds programme still in the playlist for a player, but stopped (e.g. it finished, or I paused it, but I haven't cleared the playlist) and LMS is restarted, it will start playing that programme from the last position it was started at (and not where it was paused). 

The fact that it starts automatically may admittedly be some setting I have on my player, although I've never noticed this before, but it should restart from the last position in any case. I guess I would rather it didn't restart automatically at all.

(Discovered this by being woken up in the middle of the night on server reboot ;)

**Comment by expectingtofly** [comment]
old issue no longer present
