### ISSUE TITLE
(not)running on a PPC NAS

### ISSUE THREAD

**Issue by w1ndrush** [expectingtofly/LMS_BBC_Sounds_Plugin#39]
hi, I've installed the plugin but it comes up with 'plugin failed to load' i do have it running on a test server on a laptop fine, so its not 'user error' !

I've got an old NAS with PowerPC chip running version 7.9.0 squeeze server

(looks good on my test laptop !)
Many Thanks
Andrew

**Comment by expectingtofly** [comment]
I've not tested it on 7.9.0  (I think the lowest version I tested was 7.9.3)
What is the contents of the log on reboot after trying to install?

**Comment by w1ndrush** [comment]
I’ll have a look and get back to you tomorrow. 

Thanks
