### ISSUE TITLE
Make Tracklist available in Now Playing menu

### ISSUE THREAD

**Issue by hestbank** [expectingtofly/LMS_BBC_Sounds_Plugin#52]
Please can the Tracklist be available whilst you are playing the programme. In the screen grab below of the LMS standard web view I have selected the M in the right pane which has given the options in the left hand pane. These do not include the Tracklist. 
![No Tracklist in Now Playing](https://user-images.githubusercontent.com/75666594/102542176-4f5bd080-40a9-11eb-9532-0f6605d042a9.jpg)

If I then move to a different controller, such as Squeezer on my phone or Squeeze Control on my laptop there seems to be no way of getting to the Tracklist other than going back right to the main menu, selecting BBC Sounds, My Sounds, Subscribed, Select the Series, then find the programme that you are playing - which at last gives you the option to look at the Tracklist. 

I am sure that you could get to the Segment Times (as the Tracklist was then called) from the 3 dots or 3dots and lines "Now Playing" menus in BBCiPlayer.

If there is a shortcut that I am missing please let me know. If I have not explained completely please let me know.

Many thanks.

**Comment by expectingtofly** [comment]
Sure, I'll look into adding it to the context menu next time I do a feature release

**Comment by hestbank** [comment]
Thanks.

**Comment by hestbank** [comment]
Thank you very much. ExcellentFrom: expectingtofly <notifications@github.com>Sent: Sunday, 20 December 2020, 17:40To: expectingtofly/LMS_BBC_Sounds_PluginCc: hestbank; AuthorSubject: Re: [expectingtofly/LMS_BBC_Sounds_Plugin] Make Tracklist available in Now Playing menu (#52)
Closed #52 via #53.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin/issues/52#event-4133516673",
"url": "https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin/issues/52#event-4133516673",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
