### ISSUE TITLE
Times in tracklist off by one hour

### ISSUE THREAD

**Issue by mavit** [expectingtofly/LMS_BBC_Sounds_Plugin#56]
Times displayed in tracklists start at 01:00:00 rather than 00:00:00.  Despite this, clicking "Play now" causes the stream to skip to the expected track.

**Comment by expectingtofly** [comment]
Ah, of course!  It is fine for me in the UK.  But I did a bit of a short cut to format the seconds as if it was an Epoch time, but of course that won't work outside the UK.  I'll fix that.  Thank you.

**Comment by mavit** [comment]
Curiously, I am also in the UK.

I did a bit of digging, and it turns out that the UK was [one hour ahead of GMT at the start of 1970](https://mm.icann.org/pipermail/tz/1998-January/010051.html).  I guess your OS happens to have a more naive timezone implementation and mine happens to be more historically accurate.

In any case, `gmtime` should do the trick.

**Comment by expectingtofly** [comment]
oh yes, how bizarre that I'm getting different (incorrect) results.
Thanks for the pointer.
