### ISSUE TITLE
BBC Account login

### ISSUE THREAD

**Issue by Demut** [expectingtofly/LMS_BBC_Sounds_Plugin#72]
Are there any known issues with the plugin processing BBC account logins? I have an existing account that works on the website, for iPlayer etc but it won't allow a login through the BBC Sounds LMS plugin

**Comment by expectingtofly** [comment]
There are no issues that I'm aware of.
Your LMS server needs to be able to support HTTPS / SSL to be able to login and use the plugin.
What version of LMS do you have?  
If you provide the information for "Logitech Media Server Status" that is on Settings->Information that will also indicate the version of IO::Socket::SSL you have

![image](https://user-images.githubusercontent.com/73394021/110105941-eed35a00-7da0-11eb-988b-df82a44c163d.png)

**Comment by Demut** [comment]
Thanks, I'm on 7.9.1, I rather suspect its something on my system

To be honest I'm floundering slightly trying to update to a later package or install a new source such as PinkDot to get the latest LMS. Blissfully unaware of any issues until I started getting irritating messages from the BBC telling me I won't be able to use the URLs from the 21st March and finding LMS is now EoL from Synology

**Comment by expectingtofly** [comment]
Yes, it will be the HTTPS support.  I understand it it is difficult to upgrade on Synology.  You may get some help upgrading the LMS and/or the HTTPS/SSL support on the forum.

To be honest, the easiest solution is to buy a cheap Raspberry Pi and install PiCorePlayer on it, which makes setting up LMS a breeze.  You can then just point it at your synology for accessing your music files, and you will have the up-to-date modern version of LMS.

**Comment by Demut** [comment]
Great, I'm using a couple already just as local players, I'll go that route, thanks again

**Comment by expectingtofly** [comment]
Perfect.
