### ISSUE TITLE
LMS?

### ISSUE THREAD

**Issue by steveharman** [expectingtofly/LMS_BBC_Sounds_Plugin#76]
This looks really interesting, but i couldn't find a definition of what "LMS" actually is?

Thanks

**Comment by steveharman** [comment]
Oh, there it is in the title!

**Comment by steveharman** [comment]
I think the problem comes if arriving here from a search engine like Duck or Google, which lands the user on https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin and there's no explanation of the term "LMS"

A simple edit: "BBC Sounds Plugin for LMS(Logitech Media Server)" would solve it

**Comment by expectingtofly** [comment]
Fair point, I guess
