### ISSUE TITLE
BBC Sounds search fails to find 'In Tune Mixtape' episode for 25 Mar 2021

### ISSUE THREAD

**Issue by SuffolkPunch** [expectingtofly/LMS_BBC_Sounds_Plugin#78]
Hello,

I'm running 'BBC Sounds' plug-in v.2.15.0 in LMS 7.9.1 - 1522157629 @ Fri Mar 30 12:25:29 CEST 2018.

The BBC Sounds plug-in finds the In Tune Mixtape episode for 25 Mar 2021,  if I  'drill down':  BBC Sounds > Stations & Schedules > Radio 3 > Thursday 25/03.  

However,  the BBC Sounds plug-in's search engine returns the episodes for 22,23,24 and 26 Mar but NOT 25 Mar!

Is this a known bug. Or am I not using search correctly?

**Comment by expectingtofly** [comment]
Oh yes, how bizarre.  
Alas, this is nothing to do with the plugin.  The BBC own BBC Sounds app misses the 25th March out as well! 
![image](https://user-images.githubusercontent.com/73394021/113023933-163dfc80-917e-11eb-9ca1-a85c9134e52f.png)

**Comment by SuffolkPunch** [comment]
Bizarre indeed! 

Does your plug-in  search in the same way as the BBC Sounds app itself?
